### ISSUE TITLE
how can I update all repositories daily?

### ISSUE THREAD

**Issue by Rahimianes** [xm1k3/cent#10]
Hello
How can I update all repositories daily?
I want to update all repositories that are included in .cent.yaml file.
for example, if any repo added a new template to their git repo. I will download it tomorrow into my cent-nuclei-template folder.
Thanks

**Comment by xm1k3** [comment]
Hey,
sorry for the delay, try with this simple bash script

```
cent init -o (this updates .cent.yaml to the latest version)
cent -k -p cent-nuclei-templates (this collects all nuclei templates from repos)
nuclei -l urls.txt -t ./cent-nuclei-templates -tags cve [EXAMPLE]
```

Let me know if this works for you

**Comment by Rahimianes** [comment]
Hello
Thanks for reply
But when I want to collects all nuclei templates from repos I saw the below error :

$ cent -k -p cent-nuclei-templates



**Error: required flag(s) "name" not set
Usage:
  cent [flags]
  cent [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  init        cent init project
  update      Update your repository

Flags:
      --config string   config file (default is $HOME/.cent.yaml)
  -C, --console         Print console output
  -h, --help            help for cent
  -k, --keepfolders     Keep folders (by default it only saves yaml files)
  -n, --name string     Name of the main folder
  -p, --path string     Path to save the templates

Use "cent [command] --help" for more information about a command.

required flag(s) "name" not set**


The error highlighted 
Thanks

**Comment by xm1k3** [comment]
you don't have the latest version of cent,  I had removed the flag name with version 1.0

**Comment by Rahimianes** [comment]
cent version
Error: unknown command "version" for "cent"
Run 'cent --help' for usage.
unknown command "version" for "cent"

**Comment by xm1k3** [comment]
```
GO111MODULE=on go get -u github.com/xm1k3/cent
cent version
```

**Comment by Rahimianes** [comment]
Thanks for your help.
The problem has been resolved and all repos were collected.
