### ISSUE TITLE
Need A Help From You!!!

### ISSUE THREAD

**Issue by d4715** [xm1k3/cent#11]
Hello Brother,

i hope you are doing well.
i need your help regarding all repo of nuclei-templates.
official nuclei link is this https://github.com/projectdiscovery/nuclei-templates 
we can add this link in cent tool's config file so we will get all details via cent tool with remove duplicates content.
also you know they update their repo (nuclei-templates) regularly with adding some new stuffs .
so my question is how can i getther all repo of nuclei-templates via cent tool .
latest version v8.4.9 to first release version v1.1.0
i want these all repo 
so please guide me 
Thanks.

**Comment by hakluke** [comment]
> so my question is how can i getther all repo of nuclei-templates via cent tool

Hey @d4715 - that's exactly what the tool does. All you need to do is add the repos that you want to gather into the config file, and then run the tool. The tool will then create a directory with all of the yaml files.
