### ISSUE TITLE
does not clone repositories to a directory

### ISSUE THREAD

**Issue by solo10010** [xm1k3/cent#17]
does not clone repositories to a directory

https://i.imgur.com/khHYOuJ.png

this hangs and the directory remains empty

**Comment by xm1k3** [comment]
Hi, have you checked if all GitHub repos in your `cent.yaml` are public?

**Comment by remonsec** [comment]
I am also facing same issue, using default cent config !

**Comment by abramas** [comment]
hi does not remove duplicate properly also it hang

**Comment by solo10010** [comment]
Hi 

Problems with not cloning are related to these two gist it looks like they require authorization, as a solution I suggest using my config file

https://gist.github.com/0x240x23elu
https://gist.github.com/ResistanceIsUseless/e46848f67706a8aa1205c9d2866bff31

**Comment by xm1k3** [comment]
Hello everyone, I will improve a feature to prevent these problems
if a repo in the .cent.yaml does not exist or is private, cent will automatically ignore it
