### ISSUE TITLE
the folder is empty in C disk and but when i installed D disk its worked for me, like metasploit.. did this affect with low spec device?

### ISSUE THREAD

**Issue by rabeltester44** [xm1k3/cent#35]

**Comment by xm1k3** [comment]
To better understand the situation, could you please provide more information about the specific steps you followed when installing and the error messages or symptoms you encountered? Additionally, any details about your device's specifications, such as its operating system, storage capacity, and available resources, would be helpful in diagnosing the problem.

**Comment by xm1k3** [comment]
Hi @rabeltester44 ,
closing this issue as I haven't received a reply, if there is any news feel free to reopen this issue again
