### ISSUE TITLE
Cent Error after Removing duplicate templates...

### ISSUE THREAD

**Issue by alins1r** [xm1k3/cent#4]
when start running cent its show this error :
`open .apt/usr/share/doc/zsh/changelog.gz: no such file or directory`

**Comment by xm1k3** [comment]
Hi,
I don't think that this is a cent related problem, but maybe is something about ZSH

**Comment by alins1r** [comment]
But I don't use zsh and every time I run the cent every time it show me this at the end

**Comment by xm1k3** [comment]
Hi, i have solved the problem
I pushed the update, or you can find the binary in the release part

Now cent checks if `.cent.yaml` exists before clone / dedupe stuff
```
Run cent init to automatically download .cent.yaml from repo and copy it to $HOME/.cent.yaml
```

Let me know if it works
