### ISSUE TITLE
duplicate nuclei template question

### ISSUE THREAD

**Issue by SummerSec** [xm1k3/cent#41]
Hello , I have read the project description and I have a question. Does this project download some nuclei template project files from GitHub and then de-duplicate the yaml files locally? Or is it simply downloading nuclei template files?

**Comment by xm1k3** [comment]
Yes, the project downloads nuclei template project files from GitHub and then performs a local de-duplication of the YAML files.

**Comment by SummerSec** [comment]
Can you add this item to https://github.com/tr3ss/newclei  func？

**Comment by xm1k3** [comment]
You can just call the Start() function as a library
Maybe i will create some docs examples for it

**Comment by Miracles666** [comment]
![image](https://github.com/xm1k3/cent/assets/40236845/981cbebc-53a6-4f71-8b8f-982af8bfe4ad)
performs a local de-duplication of the YAML files. It doesn't work

**Comment by xm1k3** [comment]
Can I ask you for information if the content of the Yaml is the exact same?
For deduplication, a check is carried out on the hashes, so even just one comma less is enough and the hash is different

**Comment by xm1k3** [comment]
I'm closing this issue because with the latest version I think the problem has been resolved.
If the problem is still present, feel free to reopen this issue
