### ISSUE TITLE
Clear old and corrupted repos

### ISSUE THREAD

**Issue by szybnev** [xm1k3/cent#52]
If I take on the task of cleaning up the repository list of templates that are too old and templates that don't work correctly with the current version of nuclei. Would that really make a good idea?

The main purpose of this cleanup is to remove old and non-working templates. And also to reduce the time of duplicates removal. This process takes too much time in my opinion.

@xm1k3

**Comment by xm1k3** [comment]
do you mean to create a blacklist system for templates that are no longer valid or old?

**Comment by szybnev** [comment]
Nope. I mean remove some repos with corrupted templates and templates that are always false positive/negative.

**Comment by xm1k3** [comment]
What do you propose to do? to use the --validate of nuclei?

**Comment by xm1k3** [comment]
Hey @szybnev, i have implemented i Validate command for this purpose

**Comment by Xitro01** [comment]
> Nope. I mean remove some repos with corrupted templates and templates that are always false positive/negative.

Did you ever get to this? Running all the templates as they are now, just generates a crap load of false positives.

There are a load of templates that just look at if a webapplication responds with 200 and be done with it, without verifying contents.
