### ISSUE TITLE
Cent validate "--path" flag not working

### ISSUE THREAD

**Issue by phnix-sec** [xm1k3/cent#63]
I'm trying to clear old templates but the newly added validate functionality does not work.
![image](https://github.com/xm1k3/cent/assets/16852617/4422cab5-00df-4835-93be-a3ea00411033)

**Comment by xm1k3** [comment]
Hey @phnix-sec ,
Can you check here https://github.com/xm1k3/cent/releases/tag/v1.3.1 if now is all ok? 

sorry for the delay of the response

**Comment by phnix-sec** [comment]
I just checked version 1.3.1 on two different machines and it still doesn't work.
"Error: unknown flag: --path"

**Comment by xm1k3** [comment]
Uh Sorry @phnix-sec 

just updated the repo, can I ask you to try again?
https://github.com/xm1k3/cent/releases/tag/v1.3.3

**Comment by phnix-sec** [comment]
Works now, thanks.

**Comment by phnix-sec** [comment]
Works now, thanks.
