### ISSUE TITLE
How to find the last version of yaml

### ISSUE THREAD

**Issue by neoxeo** [xm1k3/cent#7]
Sorry, it is not a real issue.

Some yaml files are present in several repo. Can you tell me how to find the most recent version of yaml file ?

I use MD5 checksum of each file to remove same yaml files but after that, in some case, there are file have the same name/id but have different MD5 checksum and I don't know hox to select the more recent file. Use date of creation of file can be use but very sure, size of file ? peraphs, or ...

Tell me if you have an idea, please ?

Thank you for the very good tool !

**Comment by xm1k3** [comment]
Hi,
at the moment `cent` does not check if the template is the most recent or not, it just removes all duplicates.
See here #1 if you want to know more about deduplication.

**Comment by xm1k3** [comment]
Closing this as I got no reply
Feel free to open a new issue for any problem.
Thanks!
